language: python

matrix:
  include:
    - python: '2.7'
      env: TOXENV=py27-coverage
    - python: '3.6'
      env: TOXENV=py36-coverage
    - python: 'pypy'
      env: TOXENV=pypy-coverage
    - python: 'pypy'
      env:
        - TOXENV=pylama
        ### As of 2016-04 Travis provides Cassandra 2.1 by default so we bundle our own
        - CASSANDRA_VERSION=3.11.1
        - CASSANDRA_STRATIO_LUCENE_VERSION=${CASSANDRA_VERSION}.0
        - CASSANDRA_HOME="${TRAVIS_BUILD_DIR}/.deps/apache-cassandra-${CASSANDRA_VERSION}/"
      # We need a java env to build and run the Lucene plugin.
      jdk: oraclejdk8
      addons:
        apt:
          packages:
            - oracle-java8-installer
    - language: java
      jdk: oraclejdk8
      env: JAVA=true
      addons:
        apt:
          packages:
            - oracle-java8-installer

env:
  global:
    - JAVA=false # Default

install:
  ### Java: We download now some dependencies to limit the number of messages later
  - if $JAVA; then mvn dependency:resolve-plugins dependency:resolve -B -V ; fi
  ### Python build dependencies
  - if [ -n "$TOXENV" ]; then pip install tox coveralls; fi
script:
  ### Java
  - if $JAVA; then mvn verify -B -V ; fi
  ### Python
  - if [ -n "$TOXENV" ]; then tox; fi
after_success:
  ### Python
  - if [ -n "$TOXENV" ]; then coveralls; fi

### sudo is required by pip
sudo: required

### As of 2016-04 Travis provides Cassandra 2.1 by default so we bundle our own
before_install:
   - ./tools/install-deps.sh
